apiVersion: apps/v1
kind: Deployment
metadata:
  name: machines-backend
  labels:
    app: machines-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machines-backend
  template:
    metadata:
      labels:
        app: machines-backend
        version: v1
    spec:
      containers:
      - name: machines-backend
        image: acrswewts.azurecr.io/machines-backend:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "sqlite:/tmp/machines.sqlite"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: machines-backend-service
  labels:
    app: machines-backend
spec:
  selector:
    app: machines-backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
