name: backend
on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "initial-data.json"
      - "dockerfile"
      - ".github/workflows/backend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: acrswewts.azurecr.io
      IMAGE: machines-backend
      VERSION: "3.0.4" 
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}

      - name: ACR login
        run: az acr login -n acrswewts

      - name: Build & push
        run: |
          docker build -t $REGISTRY/$IMAGE:$VERSION .
          docker push $REGISTRY/$IMAGE:$VERSION
